blank_issues_enabled: false
contact_links:
  - name: General Support
    url: https://support.trezor.io
    about: Please do not use this Github repository for technical support. Contact Trezor support directly or visit our community forum at forum.trezor.io.
